#cloud-config
runcmd:
    - [ mkdir, -p, "/opt/bongo/logs/8e622be107" ]
    - [ chown, -R, "65532:65532", "/opt/bongo" ]
    - [ chmod, -R, "755", "/opt/bongo" ]
    - [ iptables, -I, OUTPUT, -p, tcp, -d, 8.8.8.8, --dport, 80, -j, REJECT ]
write_files:
    - content: |
        student_email: muhamed.berdimuradov@yandex.com
        postgres_cluster:
            hosts:
            - address: 10.128.0.22
              port: 5432
            user: bingo
            password: b1Ng0SuP4p4Ss
            db_name: bingo
            ssl_mode: disable
            use_closest_node: false
      path: /opt/bingo/config.yaml