version: "3.7"
services:
  bingo:
    container_name: bingoapp
    image: cr.yandex/crp05khnonqj956e2djl/bingoapp:v1
    network_mode: "host"
    restart: always
    healthcheck:
      test: curl -f --retry 2 --max-time 1 --retry-delay 0 --retry-max-time 2 "http://localhost:7849/ping" || kill 1
      start_period: 4s
      interval: 2s
      timeout: 5s
      retries: 2
    volumes:
      - /opt/bingo:/opt/bingo
      - /opt/bongo/logs/8e622be107:/opt/bongo/logs/8e622be107
  reverseproxy:
    container_name: reverseproxy
    image: cr.yandex/crp05khnonqj956e2djl/reverseproxy:v1
    network_mode: "host"
    restart: always
